### ISSUE TITLE
Meta: Draft.js

### ISSUE THREAD

**Issue by lixiaoyan** [omega-bbs/mua#12]
## Features

- Plugins
  - [ ] Paste
  - [ ] Focus
  - [ ] Naviagte

## Enhancements

- [ ] Prevent inline style inside code block

## Bugs

- [ ] https://github.com/facebook/draft-js/issues/446
- [ ] Preserve depth after switch list type
