### ISSUE TITLE
Meta: Apollo

### ISSUE THREAD

**Issue by lixiaoyan** [omega-bbs/mua#15]
- [ ] Server side api address
- [ ] Fetch on server
- [x] babel-plugin-graphql-tag
- [ ] Batching queries
- [ ] isomorphic-fetch
- [ ] Add recompose
