### ISSUE TITLE
Meta: SSR Improvements

### ISSUE THREAD

**Issue by lixiaoyan** [omega-bbs/mua#4]
### Features

- [ ] Apollo
- [ ] Dynamic Import
- [x] ~~Production Nginx Server~~
- [x] ~~Service Worker~~

### Improvements

- [x] ~~Find a better way to let hot reload work together with caddy~~
- [x] nodemon
  - [x] nodemon rs bugs
  - [x] reduce restart times
