### ISSUE TITLE
Meta: Babel

### ISSUE THREAD

**Issue by lixiaoyan** [omega-bbs/mua#9]
- [ ] Use babel-preset-env targets
  - [ ] Different targets for client / server side
- [ ] Upgrade babel-minify (for babel 7.0)
- [x] Upgrade broken babel-plugin-styled-components (https://github.com/styled-components/babel-plugin-styled-components/pull/84)
- [x] Remove `spec: true` after https://github.com/babel/babel/issues/6153 fixed
- [ ] Decorator stage-2
  - [ ] Remove decorator
    - [ ] Use hoist-non-react-statics
